---

- name: Install buildbot_worker
  community.general.openbsd_pkg:
    name: "{{ buildbot_worker_package }}"
    state: present

- name: Install buildbot_worker_extra_packages
  community.general.openbsd_pkg:
    name: "{{ buildbot_worker_extra_packages }}"
    state: present

- name: Enable buildbot_worker_service
  ansible.builtin.service:
    name: "{{ buildbot_worker_service }}"
    enabled: yes
