---

- name: Install buildbot_worker
  pkgng:
    name: "{{ buildbot_worker_package }}"
    state: present

- name: Install buildbot_worker_extra_packages
  pkgng:
    name: "{{ buildbot_worker_extra_packages }}"
    state: present

- name: Create buildbot_worker_group
  # XXX the port does not crate user
  group:
    name: "{{ buildbot_worker_group }}"

- name: Create buildbot_worker_user
  user:
    name: "{{ buildbot_worker_user }}"
    group: "{{ buildbot_worker_group }}"
    home: "{{ buildbot_worker_conf_dir }}"

- name: Create buildbot_worker_flags file
  template:
    src: FreeBSD.rcd.j2
    dest: "/etc/rc.conf.d/{{ buildbot_worker_service | regex_replace('-', '_') }}"
    validate: sh -n %s
  notify: Restart buildbot_worker

- name: Enable buildbot_worker_service
  service:
    name: "{{ buildbot_worker_service }}"
    enabled: yes
