---
- name: Install buildbot_worker
  apt:
    name: "{{ buildbot_worker_package }}"
    state: present

- name: Create /etc/default/buildbot-worker
  template:
    src: Debian.default.j2
    dest: /etc/default/buildbot-worker
  when: 1 == 0

- name: Enable buildbot_worker_service
  service:
    name: "{{ buildbot_worker_service }}"
    enabled: yes
