---
# tasks file for ansible-role-buildbot_worker

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create buildbot_worker_root_dir directory
  file:
    path: "{{ buildbot_worker_root_dir }}"
    mode: 0755
    owner: "{{ buildbot_worker_user }}"
    group: "{{ buildbot_worker_group }}"
    state: directory
  notify: Restart buildbot_worker

- name: Create buildbot_worker_conf_dir directory
  file:
    path: "{{ buildbot_worker_conf_dir }}"
    mode: 0755
    owner: "{{ buildbot_worker_user }}"
    group: "{{ buildbot_worker_group }}"
    state: directory
  notify: Restart buildbot_worker

- name: Create buildbot_worker_conf_file
  template:
    src: buildbot.tac.j2
    dest: "{{ buildbot_worker_conf_file }}"
    owner: "{{ buildbot_worker_user }}"
    group: "{{ buildbot_worker_group }}"
    mode: 0644
  notify: Restart buildbot_worker

- name: Start buildbot_worker_service
  service:
    name: "{{ buildbot_worker_service }}"
    state: started
